site_name: satility
repo_url: https://github.com/JulioContrerasH/satility
site_url: https://JulioContrerasH.github.io/satility
site_description: This is a template repository for Python projects that use Poetry for their dependency management.
site_author: Julio Cesar Contreras Huerta
edit_uri: edit/main/docs/
repo_name: JulioContrerasH/satility
copyright: Maintained by <a href="https://JulioContrerasH.com">Florian</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append('../')
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/JulioContrerasH/satility
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/satility

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
